OpcUaClient:
  - Id: "opcua1"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://192.168.1.3:20001/Quickstarts/ReferenceServer"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    SubscriptionSamplingInterval: 0
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true
    BrowseOnStartup: true
    WriteSchemaToFile: false

  - Id: "winccoa"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://centos1.rocworks.local:4840"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    ConnectTimeout: 5000
    RequestTimeout: 5000
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0
    WriteParameters:
      QueueSize: 10000
      BlockSize: 200
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0
      DiscardOldest: true
      DataChangeTrigger: StatusValue # Status | StatusValue | StatusValueTimestamp
    BrowseOnStartup: false
    WriteSchemaToFile: false
    SubscribeOnStartup:
      - node/ns=2;s=ExampleDP_Float.ExampleDP_Arg1
      - path/$objects/Test/+/+

  - Id: "ignition"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://ubuntu1.rocworks.local:62541/discovery"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    ConnectTimeout: 5000
    RequestTimeout: 5000
    KeepAliveFailuresAllowed: 10
    SubscriptionSamplingInterval: 0
    UsernameProvider:
      Username: opcuauser
      Password: password
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: true
    MonitoringParameters:
      BufferSize: 100
      SamplingInterval: 0.0
      DiscardOldest: false
      DataChangeTrigger: StatusValueTimestamp # Status | StatusValue | StatusValueTimestamp
    BrowseOnStartup: true
    WriteSchemaToFile: false

  - Id: "unified"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://desktop-9o6hthf.rocworks.local:4890"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15
    SubscriptionSamplingInterval: 0
    UsernameProvider:
      Username: opcuauser
      Password: password1
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: true
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true
    BrowseOnStartup: false
    WriteSchemaToFile: false
