Servers:
  GraphQL:
    - Port: 4000
      LogLevel: INFO
      GraphiQL: true

  Mqtt:
    - Port: 1883
      Host: 0.0.0.0
      Enabled: true
      LogLevel: INFO # ALL | INFO

  OpcUa:
    - Port: 4842
      Enabled: true
      LogLevel: INFO      
      Topics:
        - Topic: plc/demo/node/holding-register:1:INT
        - Topic: plc/demo/node/holding-register:2:INT
        - Topic: plc/demo/node/holding-register:3:INT      

Drivers:
  Plc4x:
    - Id: "demo"
      Enabled: true
      Url: "modbus://localhost:502"
      Polling:
        Time: 100
        OldNew: true
      WriteTimeout: 100
      ReadTimeout: 100
      LogLevel: INFO    

Loggers:
  Mqtt:
    - Id: mqtt1
      Enabled: true
      Host: linux0.rocworks.local
      Port: 1883
      Ssl: false
      Topic: modbus
      Format: Raw
      Logging: 
        - Topic: plc/demo/node/holding-register:1:INT 
        - Topic: plc/demo/node/holding-register:2:INT 
        - Topic: plc/demo/node/holding-register:3:INT 