Plc4x:
  Drivers:
    - Id: "sim"
      Enabled: true
      Url: "simulated://127.0.0.1"
      LogLevel: ALL

    - Id: "opc"
      Enabled: false
      Url: "opcua:tcp://centos1:4840?discovery=false"
      LogLevel: ALL

    - Id: "mod"
      Enabled: true
      Url: "modbus://localhost:502"
      Polling:
        Time: 1000
        OldNew: true
      LogLevel: ALL