MqttServer:
  Listeners:
    - Id: Mqtt
      Port: 1883
      Host: 0.0.0.0
      LogLevel: ALL # ALL | INFO

OpcUaClient:
  - Id: "test"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://centos1:4840"
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    ConnectTimeout: 5000
    RequestTimeout: 5000
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0
    WriteParameters:
      QueueSize: 10000
      BlockSize: 200
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0
      DiscardOldest: true
