Servers:
  Mqtt:
    - Id: Mqtt
      Enabled: true
      Port: 1883
      Host: 0.0.0.0
      MaxMessageSizeKb: 8192
      #Username: demo
      #Password: demo
      LogLevel: INFO

    - Id: MqttWs
      Enabled: true
      Port: 1884
      Host: 0.0.0.0
      Websocket: true      
      MaxMessageSizeKb: 8192
      #Username: demo
      #Password: demo
      LogLevel: INFO

  GraphQL:
    - Port: 4001
      Enabled: true
      LogLevel: INFO
      GraphiQL: true      
#      Schemas:
#       - System: demo1
#       - System: demo2
#       - System: ignition
#       - System: unified
#         FieldName: DisplayName
#         RootNodes:
#           - "ns=1;s=2|Tags"

  OpcUa:
    - Port: 4841
      Enabled: true
      LogLevel: INFO
      Topics:
        - Topic: mqtt/Hivemq/path/Austria/Sparkplug/#
        - Topic: mqtt/Hivemq/node/Austria/Sparkplug/Meter/Input/Watt
        - Topic: opc/Demo2/path/Objects/Demo/SimulationMass/SimulationMass_Double/#
        - Topic: opc/Demo2/node/ns=2;s=Double_00

Drivers:  
  OpcUa:
  - Id: "demo1"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://192.168.1.3:62540/server"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0

  - Id: "demo2"
    Enabled: true
    LogLevel: INFO
    WriteSchemaToFile: false
    EndpointUrl: "opc.tcp://192.168.1.3:62541"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0

  - Id: "scada"
    Enabled: false
    LogLevel: INFO
    EndpointUrl: "opc.tcp://nuc1:4840/freeopcua/server/"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0

  - Id: "ignition"
    Enabled: false
    LogLevel: INFO
    EndpointUrl: "opc.tcp://192.168.1.3:62550/discovery"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0
    UsernameProvider:
      Username: opcuauser
      Password: password

  - Id: "winccoa"
    Enabled: false
    LogLevel: INFO
    EndpointUrl: "opc.tcp://centos1.rocworks.local:4840"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0

  - Id: "winccua"
    Enabled: false
    LogLevel: INFO
    EndpointUrl:  "opc.tcp://DESKTOP-KHLB071.rocworks.local:4890"
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15
    SubscriptionSamplingInterval: 0
    UsernameProvider:
      Username: username1
      Password: password1
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: true
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true

Loggers:
  Mqtt:
    - Id: Mqtt1
      Enabled: true
      Host: linux0.rocworks.local
      Port: 1883
      Ssl: false
      Topic: demo
      Format: Json
      BulkMessages: false                   
      LogLevel: INFO
      MaxMessageSizeKb: 1024
      Logging:
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Boolean/Boolean_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Byte/Byte_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_ByteString/ByteString_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_DateTime/DateTime_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Double/Double_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Duration/Duration_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Float/Float_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Int16/Int16_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Int32/Int32_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Int64/Int64_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_SByte/SByte_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_String/String_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_UInt16/UInt16_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_UInt32/UInt32_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_UtcTime/UtcTime_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Guid/Guid_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_LocaleId/LocaleId_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_LocalizedText/LocalizedText_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_NodeId/NodeId_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_XmlElement/XmlElement_00
  Kafka:
    - Id: Kafka1
      Enabled: false
      LogLevel: INFO
      Servers: linux0.rocworks.local:9092
      Configs:
        batch.size: 25000
        enable.auto.commit: true
        auto.commit.interval.ms: 1000
      TopicName: gateway
      Format: Json   
      Logging:
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Boolean/Boolean_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Byte/Byte_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_ByteString/ByteString_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_DateTime/DateTime_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Double/Double_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Duration/Duration_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Float/Float_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Int16/Int16_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Int32/Int32_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Int64/Int64_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_SByte/SByte_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_String/String_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_UInt16/UInt16_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_UInt32/UInt32_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_UtcTime/UtcTime_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Guid/Guid_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_LocaleId/LocaleId_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_LocalizedText/LocalizedText_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_NodeId/NodeId_00
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_XmlElement/XmlElement_00

  InfluxDB:
    - Id: Influx1
      Enabled: false
      Url: http://nuc1b.rocworks.local:8086
      Database: test
      Logging:
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Boolean/Boolean_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Byte/Byte_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_ByteString/ByteString_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_DateTime/DateTime_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Double/Double_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Duration/Duration_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Float/Float_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Int16/Int16_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Int32/Int32_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Int64/Int64_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_SByte/SByte_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_String/String_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_UInt16/UInt16_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_UInt32/UInt32_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_UtcTime/UtcTime_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Guid/Guid_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_LocaleId/LocaleId_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_LocalizedText/LocalizedText_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_NodeId/NodeId_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_XmlElement/XmlElement_00

  IoTDB:
    - Id: IotDB1
      Enabled: false
      Host: linux0.rocworks.local
      Port: 6667
      Database: root.gateway
      Username: "root"
      Password: "root"      
      Logging:
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Boolean/Boolean_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Byte/Byte_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_ByteString/ByteString_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_DateTime/DateTime_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Double/Double_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Duration/Duration_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Float/Float_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Int16/Int16_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Int32/Int32_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Int64/Int64_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_SByte/SByte_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_String/String_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_UInt16/UInt16_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_UInt32/UInt32_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_UtcTime/UtcTime_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_Guid/Guid_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_LocaleId/LocaleId_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_LocalizedText/LocalizedText_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_NodeId/NodeId_00
       - Topic: opc/demo2/path/Objects/Demo/SimulationMass/SimulationMass_XmlElement/XmlElement_00
