# Example Configuration File for the Automation Gateway
#
# Note: The OpcUaClient connections are all disabled.  
#

MqttServer:
  Listeners:
    - Id: Mqtt
      Port: 1883
      Host: 0.0.0.0
      LogLevel: INFO # ALL | INFO

    - Id: MqttWs
      Port: 1884
      Websocket: true
      Host: 0.0.0.0
      Username: system
      Password: manager
      LogLevel: INFO # ALL | INFO

GraphQLServer:
  Listeners:
    - Port: 4000
      LogLevel: INFO
      GraphiQL: true
      WriteSchemaToFile: false
      #Schemas:
      #  - System: opc1
      #    FieldName: BrowseName
      #  - System: opc2
      #    FieldName: BrowseName
      #  - System: opc3
      #    FieldName: BrowseName

OpcUaClient:
  - Id: "opc1"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://192.168.1.3:62540/server"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None

  - Id: "opc2"
    Enabled: false
    LogLevel: INFO
    EndpointUrl: "opc.tcp://192.168.1.3:62541/"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None

  - Id: "opc3"
    Enabled: false
    LogLevel: INFO
    EndpointUrl: "opc.tcp://nuc1:20003"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None

  - Id: "winccoa"
    Enabled: false
    LogLevel: INFO
    EndpointUrl: "opc.tcp://centos1:4840"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    ConnectTimeout: 5000
    RequestTimeout: 5000
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0
    WriteParameters:
      QueueSize: 10000
      BlockSize: 200
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0
      DiscardOldest: true
      DataChangeTrigger: StatusValue # Status | StatusValue | StatusValueTimestamp
    WriteSchemaToFile: false

  - Id: "ignition"
    Enabled: false
    LogLevel: INFO
    EndpointUrl: "opc.tcp://ubuntu1:62541/discovery"
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    ConnectTimeout: 5000
    RequestTimeout: 5000
    KeepAliveFailuresAllowed: 10
    SubscriptionSamplingInterval: 0
    UsernameProvider:
      Username: opcuauser
      Password: password
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: true
    MonitoringParameters:
      BufferSize: 100
      SamplingInterval: 0.0
      DiscardOldest: false
      DataChangeTrigger: StatusValueTimestamp # Status | StatusValue | StatusValueTimestamp

  - Id: "unified"
    Enabled: false
    LogLevel: INFO
    EndpointUrl:  "opc.tcp://desktop-9o6hthf:4890"
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15
    SubscriptionSamplingInterval: 0
    UsernameProvider:
      Username: opcuauser
      Password: password1
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: true
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true

  - Id: "panel"
    Enabled: false
    LogLevel: INFO
    EndpointUrl:  "opc.tcp://192.168.1.136:4890"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15
    SubscriptionSamplingInterval: 100
    UsernameProvider:
      Username: username1
      Password: password1
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: true
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 1.0
      DiscardOldest: true

Database:
  Logger:
    - Id: influx1
      Enabled: false
      Type: InfluxDB
      Url: http://nuc1:8086
      Database: test
      Username: ""
      Password: ""
      Logging:
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Float/+
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Double/+
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Int16/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Float/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Double/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Int16/+
        - Topic: opc/opc3/path/Objects/Demo/SimulationMass/SimulationMass_Float/+
        - Topic: opc/opc3/path/Objects/Demo/SimulationMass/SimulationMass_Double/+
        - Topic: opc/opc3/path/Objects/Demo/SimulationMass/SimulationMass_Int16/+

    - Id: iotdb1
      Enabled: false
      Type: IoTDB
      Host: nuc1.rocworks.local
      Port: 6667
      Database: root.scada
      Username: "root"
      Password: "root"
      Logging:
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Float/+
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Double/+
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Int16/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Float/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Double/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Int16/+
        - Topic: opc/opc3/path/Objects/Demo/SimulationMass/SimulationMass_Float/+
        - Topic: opc/opc3/path/Objects/Demo/SimulationMass/SimulationMass_Double/+
        - Topic: opc/opc3/path/Objects/Demo/SimulationMass/SimulationMass_Int16/+

    - Id: postgres1
      Type: Jdbc
      Enabled: false
      Url: jdbc:postgresql://nuc1:5432/scada
      Username: system
      Password: manager
      Logging:
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Float/+
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Double/+
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Int16/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Float/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Double/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Int16/+
        - Topic: opc/opc3/path/Objects/Demo/SimulationMass/SimulationMass_Float/+
        - Topic: opc/opc3/path/Objects/Demo/SimulationMass/SimulationMass_Double/+
        - Topic: opc/opc3/path/Objects/Demo/SimulationMass/SimulationMass_Int16/+

    - Id: mysql1
      Type: Jdbc
      Enabled: false
      Url: jdbc:mysql://nuc1:3306/scada
      Username: root
      Password: manager
      Logging:
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Float/+
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Double/+
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Int16/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Float/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Double/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Int16/+
        - Topic: opc/opc3/path/Objects/Demo/SimulationMass/SimulationMass_Float/+
        - Topic: opc/opc3/path/Objects/Demo/SimulationMass/SimulationMass_Double/+
        - Topic: opc/opc3/path/Objects/Demo/SimulationMass/SimulationMass_Int16/+

    - Id: mssql1
      Type: Jdbc
      Enabled: false
      Url: jdbc:sqlserver://nuc1;databaseName=scada
      Username: sa
      Password: Manager4711#
      Logging:
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Float/+
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Double/+
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Int16/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Float/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Double/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Int16/+
        - Topic: opc/opc3/path/Objects/Demo/SimulationMass/SimulationMass_Float/+
        - Topic: opc/opc3/path/Objects/Demo/SimulationMass/SimulationMass_Double/+
        - Topic: opc/opc3/path/Objects/Demo/SimulationMass/SimulationMass_Int16/+

    - Id: crate1
      Type: Jdbc
      Enabled: false
      Url: jdbc:crate://nuc1:5433/
      Username: crate
      Password:
      Logging:
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Float/+
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Double/+
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Int16/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Float/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Double/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Int16/+
        - Topic: opc/opc3/path/Objects/Demo/SimulationMass/SimulationMass_Float/+
        - Topic: opc/opc3/path/Objects/Demo/SimulationMass/SimulationMass_Double/+
        - Topic: opc/opc3/path/Objects/Demo/SimulationMass/SimulationMass_Int16/+

    - Id: kafka1
      Type: Kafka
      Enabled: false
      Servers: nuc1:9092
      Logging:
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Float/+
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Double/+
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Int16/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Float/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Double/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Int16/+
        - Topic: opc/opc3/path/Objects/Demo/SimulationMass/SimulationMass_Float/+
        - Topic: opc/opc3/path/Objects/Demo/SimulationMass/SimulationMass_Double/+
        - Topic: opc/opc3/path/Objects/Demo/SimulationMass/SimulationMass_Int16/+
