version: '3'
services:
  gateway:
    image: frankenstein-gateway
    hostname: gateway
    environment:
      - GATEWAY_CLUSTER_CLIENT=true
    ports: 
      - 1883:1883
      - 4000:4000
    volumes:
      - ../configs/gateway.yaml:/app/config.yaml
    networks:
      - gateway

  opcua1:
    image: frankenstein-opcua
    hostname: opcua1
    volumes:
      - ../configs/opcua1.yaml:/app/config.yaml
    networks:
      - gateway  

  opcua2:
    image: frankenstein-opcua
    hostname: opcua2
    volumes:
      - ../configs/opcua2.yaml:/app/config.yaml
    networks:
      - gateway    

  #winccoa:
  #  image: frankenstein-opcua
  #  hostname: winccoa
  #  restart: always
  #  volumes:
  #  - ../configs/winccoa.yaml:/app/config.yaml
  #  networks:
  #   - gateway  

  #ignition:
  #  image: frankenstein-opcua
  #  hostname: ignition
  #  restart: always
  #  volumes:
  #  - ../configs/ignition.yaml:/app/config.yaml
  #  networks:
  #   - gateway  

  #unified:
  #  image: frankenstein-opcua
  #  hostname: unified
  #  restart: always
  #  volumes:
  #  - ../configs/unified.yaml:/app/config.yaml
  #  networks:
  #   - gateway  

  
networks:
  gateway:

volumes:
  influxdata:
