Database:
  Logger:
    - Id: kafka1
      Type: Kafka
      Enabled: true
      Servers: 192.168.1.18:9092
      WriteParameters:
        QueueSize: 20000
        BlockSize: 10000
      Logging:
        - Topic: opc/opcua1/path/Objects/Demo/SimulationMass/SimulationMass_Double/+
        - Topic: opc/opcua1/path/Objects/Demo/SimulationMass/SimulationMass_Int16/+

