MqttServer:
  Listeners:
    - Id: Mqtt
      Port: 1883
      Host: 0.0.0.0
      LogLevel: INFO # ALL | INFO

GraphQLServer:
  Listeners:
    - Port: 4000
      LogLevel: INFO
      GraphiQL: true
      WriteSchemaToFile: false
      Schemas:
        - System: ignition
          FieldName: BrowseName # BrowseName | DisplayName
        - System: unified
          FieldName: DisplayName # BrowseName | DisplayName
        - System: winccoa
          FieldName: BrowseName # BrowseName | DisplayName

Database:
  Logger:
    - Id: default
      Type: InfluxDB
      Url: http://nuc1.rocworks.local:8086
      Database: test
      Username: ""
      Password: ""
      WriteParameters:
        QueueSize: 20000
      Logging:
        - Topic: opc/winccoa/node/ns=2;s=ExampleDP_Float.ExampleDP_Arg1
        - Topic: opc/winccoa/path/$objects/Test/+/float
        - Topic: opc/ignition/node/ns=2;s=[default]/Input_Watt

OpcUaClient:
  - Id: "winccoa"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://centos1.rocworks.local:4840"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    ConnectTimeout: 5000
    RequestTimeout: 5000
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0
    WriteParameters:
      QueueSize: 10000
      BlockSize: 200
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0
      DiscardOldest: true
      DataChangeTrigger: StatusValue # Status | StatusValue | StatusValueTimestamp
    BrowseOnStartup: false
    WriteSchemaToFile: false

  - Id: "ignition"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://ubuntu1.rocworks.local:62541/discovery"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    ConnectTimeout: 5000
    RequestTimeout: 5000
    KeepAliveFailuresAllowed: 10
    SubscriptionSamplingInterval: 0
    UsernameProvider:
      Username: opcuauser
      Password: password
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: true
    MonitoringParameters:
      BufferSize: 100
      SamplingInterval: 0.0
      DiscardOldest: false
      DataChangeTrigger: StatusValueTimestamp # Status | StatusValue | StatusValueTimestamp
    BrowseOnStartup: false
    WriteSchemaToFile: false

  - Id: "unified"
    Enabled: true
    LogLevel: INFO
    EndpointUrl:  "opc.tcp://desktop-9o6hthf.rocworks.local:4890"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15
    SubscriptionSamplingInterval: 0
    UsernameProvider:
      Username: opcuauser
      Password: password1
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: true
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true
    BrowseOnStartup: false
    WriteSchemaToFile: false
