MqttServer:
  Listeners:
    - Id: Mqtt
      Port: 1883
      Host: 0.0.0.0
      LogLevel: INFO # ALL | INFO

GraphQLServer:
  Listeners:
    - Port: 4000
      LogLevel: INFO
      GraphiQL: true
      WriteSchemaToFile: false
      Schemas:
        - System: test1
        - FieldName: BrowseName
        #- System: winccoa
        #  FieldName: BrowseName # BrowseName | DisplayName
        #- System: ignition
        #  FieldName: BrowseName # BrowseName | DisplayName
        #- System: unified
        #  FieldName: DisplayName # BrowseName | DisplayName


