MqttServer:
  Listeners:
    - Id: Mqtt
      Port: 2883
      Host: 0.0.0.0
      MaxMessageSizeKb: 8192
      #Username: demo
      #Password: demo
      LogLevel: INFO # ALL | INFO

    - Id: MqttWs
      Port: 2884
      Host: 0.0.0.0
      Websocket: true
      MaxMessageSizeKb: 8192
      #Username: demo
      #Password: demo
      LogLevel: INFO # ALL | INFO

GraphQLServer:
  Listeners:
    - Port: 4001
      Enabled: true
      LogLevel: INFO
      GraphiQL: false
      WriteSchemaToFile: false

OpcUaClient:
  - Id: "demo1"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://192.168.1.3:62540/server"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0

  - Id: "demo2"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://192.168.1.3:62541"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0

  - Id: "scada"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://nuc1:4840/freeopcua/server/"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0

  - Id: "ignition"
    Enabled: false
    LogLevel: INFO
    EndpointUrl: "opc.tcp://192.168.1.3:62550/discovery"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0
    UsernameProvider:
      Username: opcuauser
      Password: password

  - Id: "winccoa"
    Enabled: false
    LogLevel: INFO
    EndpointUrl: "opc.tcp://centos1.rocworks.local:4840"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0

  - Id: "winccua"
    Enabled: false
    LogLevel: INFO
    EndpointUrl:  "opc.tcp://DESKTOP-KHLB071.rocworks.local:4890"
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15
    SubscriptionSamplingInterval: 0
    UsernameProvider:
      Username: username1
      Password: password1
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: true
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true

MqttClient:
  - Id: "home"
    Enabled: true
    LogLevel: INFO
    Host: nuc1.rocworks.local
    Port: 1883
    #Username: ""
    #Password: ""

Database:
  Logger:
    - Id: mqtt1
      Type: Mqtt
      Enabled: true
      Host: linux0.rocworks.local
      Port: 1883
      Format: SPARKPLUGB
      WriteParameters:
        QueueSize: 20000
        BlockSize: 2000
      Topic: Enterprise/Site/Area/Line
      Logging:
        - Topic: opc/demo1/path/Objects/Variables/#
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/#
        - Topic: mqtt/home/path/Test/#

    - Id: kafka1
      Type: Kafka
      Enabled: true
      LogLevel: INFO
      Servers: linux0.rocworks.local:9092
      Configs:
        batch.size: 25000
        group.id: frankenstein-producer
        enable.auto.commit: true
        auto.commit.interval.ms: 1000
      WriteParameters:
        QueueSize: 20000
        BlockSize: 2000
      TopicName: opcua
      Logging:
        - Topic: opc/demo1/path/Objects/Variables/#
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/#

    - Id: influx1
      Type: InfluxDB
      Enabled: true
      Url: http://nuc1.rocworks.local:8086
      Database: test
      Username: ""
      Password: ""
      WriteParameters:
        QueueSize: 20000
        BlockSize: 2000
      Logging:
        - Topic: opc/demo1/path/Objects/Variables/#
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/#

