# Example Configuration File for the Automation Gateway
#
# Note: The OpcUaClient connections are all disabled.  
#

MqttServer:
  Listeners:
    - Id: Mqtt
      Enabled: true
      Port: 1883
      Host: 0.0.0.0
      LogLevel: INFO # ALL | INFO

    - Id: MqttWs
      Enabled: true
      Websocket: true      
      Port: 1884
      Host: 0.0.0.0
      Username: system
      Password: manager
      LogLevel: INFO # ALL | INFO

GraphQLServer:
  Listeners:
    - Port: 4000
      Enabled: true
      LogLevel: ALL
      GraphiQL: false
      WriteSchemaToFile: false
      #Schemas:
      #  - System: opc1
      #    FieldName: BrowseName
      #  - System: opc2
      #    FieldName: BrowseName
      #  - System: unified
      #    FieldName: DisplayName

OpcUaClient:
  - Id: "opc1"
    Enabled: false
    LogLevel: INFO
    EndpointUrl: "opc.tcp://192.168.1.3:62540/server"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None

  - Id: "opc2"
    Enabled: false
    LogLevel: INFO
    EndpointUrl: "opc.tcp://192.168.1.3:62541"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None

  - Id: "panel"
    Enabled: false
    LogLevel: INFO
    EndpointUrl:  "opc.tcp://192.168.1.136:4890"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15
    SubscriptionSamplingInterval: 100
    UsernameProvider:
      Username: username1
      Password: password1

  - Id: "unified"
    Enabled: false
    LogLevel: INFO
    EndpointUrl:  "opc.tcp://192.168.1.190:4890"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15
    SubscriptionSamplingInterval: 100
    UsernameProvider:
      Username: username1
      Password: password1

Database:
  Logger:
    - Id: influx
      Enabled: false
      Type: InfluxDB
      Url: http://192.168.1.3:8086
      Database: test
      Username: ""
      Password: ""
      WriteParameters:
        QueueSize: 20000
        BlockSize: 10000
      Logging:
      - Topic: opc/opc1/path/Objects/Dynamic/+
