Database:
  Logger:
    - Id: test
      Enabled: true
      Type: InfluxDB
      Url: http://nuc1:8086
      Database: test
      Username: ""
      Password: ""
      WriteParameters:
        QueueSize: 20000
      Logging:
        - Topic: opc/winccoa/node/ns=2;s=ExampleDP_Float.ExampleDP_Arg1
        - Topic: opc/winccoa/path/$objects/Test/+/float
        - Topic: opc/ignition/node/ns=2;s=[default]/Input_Watt
        - Topic: plc/mod/node/coil:1
        - Topic: plc/mod/node/holding-register:1:INT
        - Topic: dds/demo/path/shape/Circle
