Database:
  Logger:
    - Id: test
      Enabled: true
      Type: InfluxDB
      Url: http://nuc1:8086
      Database: test
      Username: ""
      Password: ""
      WriteParameters:
        QueueSize: 20000
      Logging:
        #- Topic: opc/winccoa/node:json/ns=2;s=ExampleDP_Float.ExampleDP_Arg1
        #- Topic: opc/winccoa/path:json/$objects/Test/+/float
        - Topic: plc/mod/node:json/coil:1
        - Topic: plc/mod/node:json/holding-register:1:INT
