OpcUaClient:
  - Id: "dotnet1"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://nuc1:62541/Quickstarts/ReferenceServer"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    SubscriptionSamplingInterval: 0
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true
    BrowseOnStartup: true
    WriteSchemaToFile: false
    WriteSchemaToCache: true
