OpcUaClient:
  - Id: "ignition"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://ubuntu1:62541/discovery"
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    ConnectTimeout: 5000
    RequestTimeout: 5000
    KeepAliveFailuresAllowed: 10
    SubscriptionSamplingInterval: 0
    UsernameProvider:
      Username: opcuauser
      Password: password
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: true
    MonitoringParameters:
      BufferSize: 100
      SamplingInterval: 0.0
      DiscardOldest: false
      DataChangeTrigger: StatusValueTimestamp # Status | StatusValue | StatusValueTimestamp
    BrowseOnStartup: false
    WriteSchemaToFile: false
