OpcUaClient:
  - Id: "test01"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://nuc1:20001/Quickstarts/ReferenceServer"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    SubscriptionSamplingInterval: 0
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true
    BrowseOnStartup: true
    WriteSchemaToFile: false
  - Id: "test02"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://nuc1:20002/Quickstarts/ReferenceServer"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    SubscriptionSamplingInterval: 0
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true
    BrowseOnStartup: true
    WriteSchemaToFile: false
  - Id: "test03"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://nuc1:20003/Quickstarts/ReferenceServer"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    SubscriptionSamplingInterval: 0
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true
    BrowseOnStartup: true
    WriteSchemaToFile: false
    WriteSchemaToCache: true
  - Id: "test04"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://nuc1:20004/Quickstarts/ReferenceServer"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    SubscriptionSamplingInterval: 0
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true
    BrowseOnStartup: true
    WriteSchemaToFile: false
  - Id: "test05"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://nuc1:20005/Quickstarts/ReferenceServer"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    SubscriptionSamplingInterval: 0
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true
    BrowseOnStartup: true
    WriteSchemaToFile: false
  - Id: "test06"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://nuc1:20006/Quickstarts/ReferenceServer"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    SubscriptionSamplingInterval: 0
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true
    BrowseOnStartup: true
    WriteSchemaToFile: false
  - Id: "test07"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://nuc1:20007/Quickstarts/ReferenceServer"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    SubscriptionSamplingInterval: 0
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true
    BrowseOnStartup: true
    WriteSchemaToFile: false
  - Id: "test08"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://nuc1:20008/Quickstarts/ReferenceServer"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    SubscriptionSamplingInterval: 0
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true
    BrowseOnStartup: true
    WriteSchemaToFile: false
    WriteSchemaToCache: true
  - Id: "test09"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://nuc1:20009/Quickstarts/ReferenceServer"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    SubscriptionSamplingInterval: 0
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true
    BrowseOnStartup: true
    WriteSchemaToFile: false
  - Id: "test10"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://nuc1:20010/Quickstarts/ReferenceServer"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    SubscriptionSamplingInterval: 0
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true
    BrowseOnStartup: true
    WriteSchemaToFile: false
