OpcUaClient:
  - Id: "demo"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://192.168.1.3:62541"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0 

Database:
  Logger:
    - Id: mqtt1
      Type: Mqtt
      Enabled: true
      Host: bd9c43f59b7a42deba3248fca439f378.s1.eu.hivemq.cloud
      Username: vogler
      Password: GzT!xPdFn4j6Czr
      Port: 8883
      Ssl: true
      WriteParameters:
        QueueSize: 20000
        BlockSize: 10000
      Topic: Enterprise/Site
      Logging:
        - Topic: opc/demo/path/Objects/Demo/SimulationMass/#