MqttServer:
  Listeners:
    - Id: Mqtt
      Port: 1883
      Host: 0.0.0.0
      LogLevel: INFO # ALL | INFO

GraphQLServer:
  Listeners:
    - Port: 4000
      LogLevel: INFO
      GraphiQL: true
      WriteSchemaToFile: false
      Schemas:

MqttClient:
  - Id: "mqtt1"
    Enabled: true
    LogLevel: INFO
    Host: raspberry1
    Port: 1883
    Ssl: false
