MqttServer:
  Listeners:
    - Id: Mqtt
      Port: 1883
      Host: 0.0.0.0
      LogLevel: INFO # ALL | INFO

GraphQLServer:
  Listeners:
    - Port: 4000
      LogLevel: INFO
      GraphiQL: true
      WriteSchemaToFile: false
      Schemas:
      - System: opc1
        
      #  - System: ignition
      #    FieldName: BrowseName # BrowseName | DisplayName
      #  - System: unified
      #    FieldName: DisplayName # BrowseName | DisplayName
      #  - System: winccoa
      #    FieldName: BrowseName # BrowseName | DisplayName

Database:
  Logger:
    - Id: kafka1
      Type: Kafka
      Enabled: true
      Servers: 192.168.1.131:9092
      Configs:
        batch.size: 25000
        group.id: frankenstein-producer
        enable.auto.commit: true
        auto.commit.interval.ms: 1000
      WriteParameters:
        QueueSize: 10000
        BlockSize: 1000
      TopicName: test # default is the system id of the topic      
      #KeyName: test # default is the node path name
      Logging:
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_SByte/+
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Byte/+
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Float/+
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Double/+
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Integer/+
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Int16/+
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Int32/+
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Int64/+
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_Unt16/+
        - Topic: opc/opc1/path/Objects/Demo/SimulationMass/SimulationMass_UInt32/+

        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_SByte/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Byte/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Float/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Double/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Integer/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Int16/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Int32/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Int64/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_Unt16/+
        - Topic: opc/opc2/path/Objects/Demo/SimulationMass/SimulationMass_UInt32/+

OpcUaClient:
  - Id: "opc1"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://192.168.1.131:20011"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    ConnectTimeout: 5000
    RequestTimeout: 5000
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0
    WriteParameters:
      QueueSize: 10000
      BlockSize: 200
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0
      DiscardOldest: true
      DataChangeTrigger: StatusValue # Status | StatusValue | StatusValueTimestamp
 
  - Id: "opc2"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://192.168.1.131:20011"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    ConnectTimeout: 5000
    RequestTimeout: 5000
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0
    WriteParameters:
      QueueSize: 10000
      BlockSize: 200
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0
      DiscardOldest: true
      DataChangeTrigger: StatusValue # Status | StatusValue | StatusValueTimestamp
  
  - Id: "winccoa"
    Enabled: false
    LogLevel: INFO
    EndpointUrl: "opc.tcp://centos1:4840"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    ConnectTimeout: 5000
    RequestTimeout: 5000
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0
    WriteParameters:
      QueueSize: 10000
      BlockSize: 200
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0
      DiscardOldest: true
      DataChangeTrigger: StatusValue # Status | StatusValue | StatusValueTimestamp
 
  - Id: "ignition"
    Enabled: false
    LogLevel: INFO
    EndpointUrl: "opc.tcp://ubuntu1:62541/discovery"
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    ConnectTimeout: 5000
    RequestTimeout: 5000
    KeepAliveFailuresAllowed: 10
    SubscriptionSamplingInterval: 0
    UsernameProvider:
      Username: opcuauser
      Password: password
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: true
    MonitoringParameters:
      BufferSize: 100
      SamplingInterval: 0.0
      DiscardOldest: false
      DataChangeTrigger: StatusValueTimestamp # Status | StatusValue | StatusValueTimestamp
 
  - Id: "unified"
    Enabled: false
    LogLevel: INFO
    EndpointUrl:  "opc.tcp://desktop-9o6hthf:4890"
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15
    SubscriptionSamplingInterval: 0
    UsernameProvider:
      Username: opcuauser
      Password: password1
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: true
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true
