Servers:
  Mqtt:
    - Port: 1883
      Host: 0.0.0.0
      LogLevel: INFO # ALL | INFO

  GraphQL:
    - Port: 4000
      LogLevel: INFO
      GraphiQL: true
      WriteSchemaToFile: false

Drivers:
  Mqtt:
  - Id: "mqtt1"
    Enabled: true
    LogLevel: INFO
    Host: 192.168.1.6
    Port: 1883
    Ssl: false    

Loggers:
  InfluxDB:
    - Id: influx1
      Enabled: true      
      Url: http://nuc1.rocworks.local:8086
      Database: test
      Username: ""
      Password: ""
      WriteParameters:
        QueueSize: 20000
        BlockSize: 10000
      Logging:
        - Topic: mqtt/mqtt1/path/Meter_Input/WattAct
        - Topic: mqtt/mqtt1/path/Meter_Output/WattAct
        - Topic: mqtt/mqtt1/path/PV/Spot/+