version: '3'
services:
  cache1:
    image: frankenstein-cache
    hostname: cache1
    environment:
      - GATEWAY_CLUSTER_TYPE=ignite    
      - IGNITE_CLIENT_MODE=false
      - IGNITE_CLUSTER_HOST=*
      - IGNITE_CLUSTER_PORT=15701
    volumes:
      - ../configs/cache1.yaml:/app/config.yaml
    ports:
      - 10800:10800       
    networks:
      - gateway

  # cache2:
  #   image: frankenstein-cache
  #   hostname: cache2
  #   environment:
  #     - GATEWAY_CLUSTER_TYPE=ignite    
  #     - IGNITE_CLIENT_MODE=false
  #     - IGNITE_CLUSTER_HOST=*
  #     - IGNITE_CLUSTER_PORT=15701
  #   volumes:
  #     - ../configs/cache2.yaml:/app/config.yaml
  #   ports:
  #     - 10801:10800       
  #   networks:
  #     - gateway      

  gateway:
    image: frankenstein-gateway
    hostname: gateway1
    environment:
      - GATEWAY_CLUSTER_TYPE=ignite  
      - IGNITE_CLIENT_MODE=true
      - IGNITE_CLUSTER_HOST=*
      - IGNITE_CLUSTER_PORT=15701
    ports: 
      - 1883:1883
      - 4000:4000
    volumes:
      - ../configs/gateway.yaml:/app/config.yaml
    networks:
      - gateway
    depends_on:
      - cache1

  opcua1:
    image: frankenstein-opcua
    hostname: opcua1
    environment:
      - GATEWAY_CLUSTER_TYPE=ignite  
      - IGNITE_CLIENT_MODE=true
      - IGNITE_CLUSTER_HOST=*
      - IGNITE_CLUSTER_PORT=15701
    volumes:
      - ../configs/opcua1.yaml:/app/config.yaml
    networks:
      - gateway  
    depends_on: 
      - cache1

  # opcua2:
  #   image: frankenstein-opcua
  #   hostname: opcua2
  #   environment:
  #     - GATEWAY_CLUSTER_TYPE=ignite  
  #     - IGNITE_CLIENT_MODE=true
  #     - IGNITE_CLUSTER_HOST=*
  #     - IGNITE_CLUSTER_PORT=15701
  #   volumes:
  #     - ../configs/opcua2.yaml:/app/config.yaml
  #   networks:
  #     - gateway  
  #   depends_on:
  #     - cache1     

  # winccoa:
  #   image: frankenstein-opcua
  #   hostname: winccoa
  #   environment:
  #     - GATEWAY_CLUSTER_TYPE=ignite  
  #     - IGNITE_CLIENT_MODE=true
  #     - IGNITE_CLUSTER_HOST=*
  #     - IGNITE_CLUSTER_PORT=15701  
  #   restart: always
  #   volumes:
  #   - ../configs/winccoa.yaml:/app/config.yaml
  #   networks:
  #    - gateway  

  # ignition:
  #   image: frankenstein-opcua
  #   hostname: ignition
  #   environment:
  #     - GATEWAY_CLUSTER_TYPE=ignite  
  #     - IGNITE_CLIENT_MODE=true
  #     - IGNITE_CLUSTER_HOST=*
  #     - IGNITE_CLUSTER_PORT=15701      
  #   restart: always
  #   volumes:
  #   - ../configs/ignition.yaml:/app/config.yaml
  #   networks:
  #    - gateway  

  # unified:
  #   image: frankenstein-opcua
  #   hostname: unified
  #   environment:
  #     - GATEWAY_CLUSTER_TYPE=ignite  
  #     - IGNITE_CLIENT_MODE=true
  #     - IGNITE_CLUSTER_HOST=*
  #     - IGNITE_CLUSTER_PORT=15701      
  #   restart: always
  #   volumes:
  #     - ../configs/unified.yaml:/app/config.yaml
  #   networks:
  #   - gateway  

  # ignite1:
  #   image: apacheignite/ignite:2.9.1
  #   restart: always
  #   volumes:
  #     - ./libs:/opt/ignite/apache-ignite/libs/user_libs
  #   networks:
  #     - gateway
  #   ports:
  #     - 10800:10800     

  # ignite2:
  #   image: apacheignite/ignite:2.9.1
  #   restart: always
  #   volumes:
  #     - ./libs:/opt/ignite/apache-ignite/libs/user_libs
  #   networks:
  #     - gateway

  # ignite3:
  #   image: apacheignite/ignite:2.9.1
  #   restart: always
  #   volumes:
  #     - ./libs:/opt/ignite/apache-ignite/libs/user_libs
  #   networks:
  #     - gateway     

  
networks:
  gateway:

volumes:
  influxdata:    
