MqttServer:
  Listeners:
    - Id: Mqtt
      Port: 1883
      Host: 0.0.0.0
      LogLevel: ALL # ALL | INFO

GraphQLServer:
  Listeners:
    - Port: 4000
    - LogLevel: ALL

Database:
  Logger:
    - Id: default
      Type: InfluxDB
      #Url: http://nuc1:8086
      Url: http://server2:8086
      Database: test
      Username: ""
      Password: ""
      WriteParameters:
        QueueSize: 20000
      Logging:
        - Topic: opc/oa1/path:json/$objects/Test/+/float
        #- Topic: opc/oa2/path:json/$objects/Test/+/float
        #- Topic: opc/oa3/path:json/$objects/Test/+/float
        #- Topic: opc/oa1/path:json/$objects/ExampleDP_Float/+
        #- Topic: opc/oa2/path:json/$objects/ExampleDP_Float/+
        #- Topic: opc/ignition/path:json/$objects/Tag Providers/default/_Sim1_/Ramp/+
        #- Topic: opc/ua/path:json/ns=1;s=16|Tags/+
        #- Topic: opc/ucp/path:json/ns=1;s=3|Tags/+

OpcUaClient:
  - Id: "oa1"
    Enabled: true
    LogLevel: ALL
    EndpointUrl: "opc.tcp://centos1.rocworks.local:4840"
    UpdateEndpointUrl: centos1.rocworks.local
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    ConnectTimeout: 5000
    RequestTimeout: 5000
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0
    WriteParameters:
      QueueSize: 10000
      BlockSize: 100
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0
      DiscardOldest: true

  - Id: "oa2"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://192.168.1.100:4840"
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    ConnectTimeout: 5000
    RequestTimeout: 5000
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0
    WriteParameters:
      QueueSize: 10000
      BlockSize: 100
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0
      DiscardOldest: true

  - Id: "oa3"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://192.168.1.103:4840"
    UpdateEndpointUrl: 192.168.1.103
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    ConnectTimeout: 5000
    RequestTimeout: 5000
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0
    WriteParameters:
      QueueSize: 10000
      BlockSize: 100
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0
      DiscardOldest: true

  - Id: "ignition"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://ubuntu1:62541/discovery"
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    ConnectTimeout: 5000
    RequestTimeout: 5000
    KeepAliveFailuresAllowed: 10
    SubscriptionSamplingInterval: 0
    UsernameProvider:
      Username: opcuauser
      Password: password
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: true
    MonitoringParameters:
      BufferSize: 100
      SamplingInterval: 0.0
      DiscardOldest: false
    Subscriptions:
      - Topic: opc/ignition/path:json/$objects/Tag Providers/default/_Sim1_/Ramp/+

  - Id: "ua"
    Enabled: true
    LogLevel: INFO
    EndpointUrl:  "opc.tcp://desktop-9o6hthf:4890"
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15
    SubscriptionSamplingInterval: 0
    UsernameProvider:
      Username: opcuauser
      Password: password1
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: true
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true

  - Id: "ucp"
    Enabled: true
    LogLevel: INFO
    EndpointUrl:  "opc.tcp://192.168.1.137:4890"
    UpdateEndpointUrl: 192.168.1.137
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15
    SubscriptionSamplingInterval: 0
    UsernameProvider:
      Username: opcuauser
      Password: password1
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: true
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true