OpcUaClient:
  - Id: "ignition"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://ubuntu1.rocworks.local:62541/discovery"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    ConnectTimeout: 5000
    RequestTimeout: 5000
    KeepAliveFailuresAllowed: 10
    SubscriptionSamplingInterval: 0
    UsernameProvider:
      Username: opcuauser
      Password: password
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: true
    MonitoringParameters:
      BufferSize: 100
      SamplingInterval: 0.0
      DiscardOldest: false
      DataChangeTrigger: StatusValueTimestamp # Status | StatusValue | StatusValueTimestamp
    SubscribeOnStartup:
      - node/ns=2;s=[default]/Pump_1/flow
      - node/ns=2;s=[default]/Pump_1/speed