OpcUaClient:
  - Id: "opcua1"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://192.168.1.3:20001/Quickstarts/ReferenceServer"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    SubscriptionSamplingInterval: 0
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true
    BrowseOnStartup: true
    WriteSchemaToFile: false
  - Id: "opcua2"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://192.168.1.3:20002/Quickstarts/ReferenceServer"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    SubscriptionSamplingInterval: 0
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true
    BrowseOnStartup: true
    WriteSchemaToFile: false     
  - Id: "opcua3"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://192.168.1.3:20003/Quickstarts/ReferenceServer"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    SubscriptionSamplingInterval: 0
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true
    BrowseOnStartup: true
    WriteSchemaToFile: false      
  - Id: "opcua4"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://192.168.1.3:20004/Quickstarts/ReferenceServer"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    SubscriptionSamplingInterval: 0
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true
    BrowseOnStartup: true
    WriteSchemaToFile: false   
  - Id: "opcua5"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://192.168.1.3:20005/Quickstarts/ReferenceServer"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    SubscriptionSamplingInterval: 0
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: false
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true
    BrowseOnStartup: true
    WriteSchemaToFile: false       